project_id = "xqmfdoayucknepabazpp"

[functions.send-contact-email]
verify_jwt = false

[functions.send-order-status-email]
verify_jwt = true

[functions.generate-christmas-menu-pdf]
verify_jwt = false